[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL"

[[redirects]]
  from = "/entrega/*"
  to = "/entrega.html"
  status = 200

[[redirects]]
  from = "/separacao/*"
  to = "/separacao.html"
  status = 200

[[redirects]]
  from = "/romaneio/:id/imprimir"
  to = "/.netlify/functions/romaneio-imprimir?id=:id"
  status = 200
